<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Quantium Virtual Internship - Retail Strategy and Analytics - Task 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="forage_quantium_task1_files/libs/clipboard/clipboard.min.js"></script>
<script src="forage_quantium_task1_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="forage_quantium_task1_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="forage_quantium_task1_files/libs/quarto-html/popper.min.js"></script>
<script src="forage_quantium_task1_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="forage_quantium_task1_files/libs/quarto-html/anchor.min.js"></script>
<link href="forage_quantium_task1_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="forage_quantium_task1_files/libs/quarto-html/quarto-syntax-highlighting-53f539a478d6ecd1be31ce9fd30fd81c.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="forage_quantium_task1_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="forage_quantium_task1_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="forage_quantium_task1_files/libs/bootstrap/bootstrap-b0d41b5f0083078154ce357f865e1e3e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Quantium Virtual Internship - Retail Strategy and Analytics - Task 1</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="solution-template-for-task-1" class="level1">
<h1>Solution template for Task 1</h1>
<p>This file is a solution template for the Task 1 of the Quantium Virtual Internship. It will walk you through the analysis, providing the scaffolding for your solution with gaps left for you to fill in yourself.</p>
<p>Look for comments that say “over to you” for places where you need to add your own code! Often, there will be hints about what to do or what function to use in the text leading up to a code block - if you need a bit of extra help on how to use a function, the internet has many excellent resources on R coding, which you can find using your favourite search engine.</p>
<section id="load-required-libraries-and-datasets" class="level2">
<h2 class="anchored" data-anchor-id="load-required-libraries-and-datasets">Load required libraries and datasets</h2>
<p>Note that you will need to install these libraries if you have never used these before.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Example code to install packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("data.table")</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="do">#### Load required libraries</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggmosaic)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:data.table':

    between, first, last</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Point the filePath to where you have downloaded the datasets to and assign the data files to data.tables</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># over to you! fill in the path to your working directory. If you are on a Windows machine, you will need to use forward slashes (/) instead of backshashes (\)</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>filePath <span class="ot">&lt;-</span> <span class="st">"data/"</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>transactionData <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="fu">paste0</span>(filePath,<span class="st">"QVI_transaction_data.csv"</span>))</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>customerData <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="fu">paste0</span>(filePath,<span class="st">"QVI_purchase_behaviour.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory data analysis</h2>
<p>The first step in any analysis is to first understand the data. Let’s take a look at each of the datasets provided.</p>
<section id="examining-transaction-data" class="level3">
<h3 class="anchored" data-anchor-id="examining-transaction-data">Examining transaction data</h3>
<p>We can use <code>str()</code> to look at the format of each column and see a sample of the data. As we have read in the dataset as a <code>data.table</code> object, we can also run <code>transactionData</code> in the console to see a sample of the data or use <code>head(transactionData)</code> to look at the first 10 rows. Let’s check if columns we would expect to be numeric are in numeric form and date columns are in date format.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Examine transaction data</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you! Examine the data using one or more of the methods described above.</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(transactionData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Classes 'data.table' and 'data.frame': 264836 obs. of 8 variables:
$ DATE : int 43390 43599 43605 43329 43330 43604 43601 43601 43332 43330 ...
$ STORE_NBR : int 1 1 1 2 2 4 4 4 5 7 ...
$ LYLTY_CARD_NBR: int 1000 1307 1343 2373 2426 4074 4149 4196 5026 7150 ...
$ TXN_ID : int 1 348 383 974 1038 2982 3333 3539 4525 6900 ...
$ PROD_NBR : int 5 66 61 69 108 57 16 24 42 52 ...
$ PROD_NAME : chr "Natural Chip Compny SeaSalt175g" "CCs Nacho Cheese 175g"
"Smiths Crinkle Cut Chips Chicken 170g" "Smiths Chip Thinly S/Cream&amp;Onion 175g"
...
$ PROD_QTY : int 2 3 2 5 3 1 1 1 1 2 ...
$ TOT_SALES : num 6 6.3 2.9 15 13.8 5.1 5.7 3.6 3.9 7.2 ...
- attr(*, ".internal.selfref")=&lt;externalptr&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(transactionData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    DATE STORE_NBR LYLTY_CARD_NBR TXN_ID PROD_NBR
   &lt;int&gt;     &lt;int&gt;          &lt;int&gt;  &lt;int&gt;    &lt;int&gt;
1: 43390         1           1000      1        5
2: 43599         1           1307    348       66
3: 43605         1           1343    383       61
4: 43329         2           2373    974       69
5: 43330         2           2426   1038      108
6: 43604         4           4074   2982       57
                                  PROD_NAME PROD_QTY TOT_SALES
                                     &lt;char&gt;    &lt;int&gt;     &lt;num&gt;
1:   Natural Chip        Compny SeaSalt175g        2       6.0
2:                 CCs Nacho Cheese    175g        3       6.3
3:   Smiths Crinkle Cut  Chips Chicken 170g        2       2.9
4:   Smiths Chip Thinly  S/Cream&amp;Onion 175g        5      15.0
5: Kettle Tortilla ChpsHny&amp;Jlpno Chili 150g        3      13.8
6: Old El Paso Salsa   Dip Tomato Mild 300g        1       5.1</code></pre>
</div>
</div>
<p>We can see that the date column is in an integer format. Let’s change this to a date format.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Convert DATE column to a date format</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="do">#### A quick search online tells us that CSV and Excel integer dates begin on 30 Dec 1899</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>transactionData<span class="sc">$</span>DATE <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(transactionData<span class="sc">$</span>DATE, <span class="at">origin =</span> <span class="st">"1899-12-30"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We should check that we are looking at the right products by examining <code>PROD_NAME</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Examine PROD_NAME</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you! Generate a summary of the PROD_NAME column.</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(transactionData<span class="sc">$</span>PROD_NAME)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Length     Class      Mode 
   264836 character character </code></pre>
</div>
</div>
<p>Looks like we are definitely looking at potato chips but how can we check that these are all chips? We can do some basic text analysis by summarising the individual words in the product name.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Examine the words in PROD_NAME to see if there are any incorrect entries such as products that are not chips</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>productWords <span class="ot">&lt;-</span> <span class="fu">data.table</span>(<span class="fu">unlist</span>(<span class="fu">strsplit</span>(<span class="fu">unique</span>(transactionData[, PROD_NAME]), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)))</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">setnames</span>(productWords, <span class="st">'words'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As we are only interested in words that will tell us if the product is chips or not, let’s remove all words with digits and special characters such as ‘&amp;’ from our set of product words. We can do this using <code>grepl()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you! Remove digits, and special characters, and then sort the distinct words by frequency of occurrence.</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="do">#### Removing digits and special characters</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>productWords[, words_clean <span class="sc">:</span><span class="er">=</span> <span class="fu">trimws</span>(</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gsub</span>(<span class="st">" +"</span>, <span class="st">" "</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>       <span class="fu">gsub</span>(<span class="st">"[Gg]$"</span>, <span class="st">""</span>, <span class="co"># remove trailing 'g' only</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>            <span class="fu">gsub</span>(<span class="st">"[^A-Za-z ]"</span>, <span class="st">""</span>, words) <span class="co"># remove non-letter/space chars</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>       )</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>)]</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(productWords)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                      words                        words_clean
                                     &lt;char&gt;                             &lt;char&gt;
1:   Natural Chip        Compny SeaSalt175g        Natural Chip Compny SeaSalt
2:                 CCs Nacho Cheese    175g                   CCs Nacho Cheese
3:   Smiths Crinkle Cut  Chips Chicken 170g   Smiths Crinkle Cut Chips Chicken
4:   Smiths Chip Thinly  S/Cream&amp;Onion 175g     Smiths Chip Thinly SCreamOnion
5: Kettle Tortilla ChpsHny&amp;Jlpno Chili 150g Kettle Tortilla ChpsHnyJlpno Chili
6: Old El Paso Salsa   Dip Tomato Mild 300g  Old El Paso Salsa Dip Tomato Mild</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># #### Removing digits</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># productWords &lt;- productWords[grepl("\\d", words) == FALSE, ]</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># #### Removing special characters</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># productWords &lt;- productWords[grepl("[:alpha:]", words), ]</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="do">#### Let's look at the most common words by counting the number of times a word appears and sorting them by this frequency in order of highest to lowest frequency</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Split each phrase into individual words</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>word_list <span class="ot">&lt;-</span> <span class="fu">strsplit</span>(productWords<span class="sc">$</span>words_clean, <span class="st">" "</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Flatten the list into one vector of words</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>all_words <span class="ot">&lt;-</span> <span class="fu">unlist</span>(word_list)</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Count and sort by frequency</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>word_freq <span class="ot">&lt;-</span> <span class="fu">data.table</span>(<span class="at">word =</span> all_words)[, .N, by <span class="ot">=</span> word][<span class="fu">order</span>(<span class="sc">-</span>N)]</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(word_freq)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      word     N
    &lt;char&gt; &lt;int&gt;
1:   Chips    21
2:  Smiths    16
3: Crinkle    14
4:     Cut    14
5:  Kettle    13
6:  Cheese    12</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># #### Let's look at the most common words by counting the number of times a word appears and sorting them by this frequency in order of highest to lowest frequency</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># productWords[, .N, words][order(N, decreasing = TRUE)]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There are salsa products in the dataset but we are only interested in the chips category, so let’s remove these.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Remove salsa products</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>transactionData[, SALSA <span class="sc">:</span><span class="er">=</span> <span class="fu">grepl</span>(<span class="st">"salsa"</span>, <span class="fu">tolower</span>(PROD_NAME))]</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>transactionData <span class="ot">&lt;-</span> transactionData[SALSA <span class="sc">==</span> <span class="cn">FALSE</span>, ][, SALSA <span class="sc">:</span><span class="er">=</span> <span class="cn">NULL</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we can use <code>summary()</code> to check summary statistics such as mean, min and max values for each feature to see if there are any obvious outliers in the data and if there are any nulls in any of the columns (<code>NA's : number of nulls</code> will appear in the output if there are any nulls).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Summarise the data to check for nulls and possible outliers</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you!</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(transactionData, <span class="cf">function</span>(x) <span class="fu">sum</span>(<span class="fu">is.na</span>(x)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          DATE      STORE_NBR LYLTY_CARD_NBR         TXN_ID       PROD_NBR 
             0              0              0              0              0 
     PROD_NAME       PROD_QTY      TOT_SALES 
             0              0              0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(transactionData, <span class="cf">function</span>(x) <span class="fu">sum</span>(<span class="fu">is.null</span>(x)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          DATE      STORE_NBR LYLTY_CARD_NBR         TXN_ID       PROD_NBR 
             0              0              0              0              0 
     PROD_NAME       PROD_QTY      TOT_SALES 
             0              0              0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(transactionData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      DATE              STORE_NBR     LYLTY_CARD_NBR        TXN_ID       
 Min.   :2018-07-01   Min.   :  1.0   Min.   :   1000   Min.   :      1  
 1st Qu.:2018-09-30   1st Qu.: 70.0   1st Qu.:  70015   1st Qu.:  67569  
 Median :2018-12-30   Median :130.0   Median : 130367   Median : 135183  
 Mean   :2018-12-30   Mean   :135.1   Mean   : 135531   Mean   : 135131  
 3rd Qu.:2019-03-31   3rd Qu.:203.0   3rd Qu.: 203084   3rd Qu.: 202654  
 Max.   :2019-06-30   Max.   :272.0   Max.   :2373711   Max.   :2415841  
    PROD_NBR       PROD_NAME            PROD_QTY         TOT_SALES      
 Min.   :  1.00   Length:246742      Min.   :  1.000   Min.   :  1.700  
 1st Qu.: 26.00   Class :character   1st Qu.:  2.000   1st Qu.:  5.800  
 Median : 53.00   Mode  :character   Median :  2.000   Median :  7.400  
 Mean   : 56.35                      Mean   :  1.908   Mean   :  7.321  
 3rd Qu.: 87.00                      3rd Qu.:  2.000   3rd Qu.:  8.800  
 Max.   :114.00                      Max.   :200.000   Max.   :650.000  </code></pre>
</div>
</div>
<p>There are no nulls in the columns but product quantity appears to have an outlier which we should investigate further. Let’s investigate further the case where 200 packets of chips are bought in one transaction.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Filter the dataset to find the outlier</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you! Use a filter to examine the transactions in question.</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>outlier <span class="ot">&lt;-</span> transactionData[PROD_QTY <span class="sc">==</span> <span class="dv">200</span>]</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>outlier</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         DATE STORE_NBR LYLTY_CARD_NBR TXN_ID PROD_NBR
       &lt;Date&gt;     &lt;int&gt;          &lt;int&gt;  &lt;int&gt;    &lt;int&gt;
1: 2018-08-19       226         226000 226201        4
2: 2019-05-20       226         226000 226210        4
                          PROD_NAME PROD_QTY TOT_SALES
                             &lt;char&gt;    &lt;int&gt;     &lt;num&gt;
1: Dorito Corn Chp     Supreme 380g      200       650
2: Dorito Corn Chp     Supreme 380g      200       650</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>outlier_customer <span class="ot">&lt;-</span> <span class="fu">unique</span>(outlier<span class="sc">$</span>LYLTY_CARD_NBR) <span class="co"># 226000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There are two transactions where 200 packets of chips are bought in one transaction and both of these transactions were by the same customer.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Let's see if the customer has had other transactions</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you! Use a filter to see what other transactions that customer made.</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>transactionData[LYLTY_CARD_NBR <span class="sc">==</span> outlier_customer]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         DATE STORE_NBR LYLTY_CARD_NBR TXN_ID PROD_NBR
       &lt;Date&gt;     &lt;int&gt;          &lt;int&gt;  &lt;int&gt;    &lt;int&gt;
1: 2018-08-19       226         226000 226201        4
2: 2019-05-20       226         226000 226210        4
                          PROD_NAME PROD_QTY TOT_SALES
                             &lt;char&gt;    &lt;int&gt;     &lt;num&gt;
1: Dorito Corn Chp     Supreme 380g      200       650
2: Dorito Corn Chp     Supreme 380g      200       650</code></pre>
</div>
</div>
<p>It looks like this customer has only had the two transactions over the year and is not an ordinary retail customer. The customer might be buying chips for commercial purposes instead. We’ll remove this loyalty card number from further analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Filter out the customer based on the loyalty card number</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you!</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>transactionData <span class="ot">&lt;-</span> transactionData[LYLTY_CARD_NBR <span class="sc">!=</span> outlier_customer]</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="do">#### Re-examine transaction data</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you!</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(transactionData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      DATE              STORE_NBR     LYLTY_CARD_NBR        TXN_ID       
 Min.   :2018-07-01   Min.   :  1.0   Min.   :   1000   Min.   :      1  
 1st Qu.:2018-09-30   1st Qu.: 70.0   1st Qu.:  70015   1st Qu.:  67569  
 Median :2018-12-30   Median :130.0   Median : 130367   Median : 135182  
 Mean   :2018-12-30   Mean   :135.1   Mean   : 135530   Mean   : 135130  
 3rd Qu.:2019-03-31   3rd Qu.:203.0   3rd Qu.: 203083   3rd Qu.: 202652  
 Max.   :2019-06-30   Max.   :272.0   Max.   :2373711   Max.   :2415841  
    PROD_NBR       PROD_NAME            PROD_QTY       TOT_SALES     
 Min.   :  1.00   Length:246740      Min.   :1.000   Min.   : 1.700  
 1st Qu.: 26.00   Class :character   1st Qu.:2.000   1st Qu.: 5.800  
 Median : 53.00   Mode  :character   Median :2.000   Median : 7.400  
 Mean   : 56.35                      Mean   :1.906   Mean   : 7.316  
 3rd Qu.: 87.00                      3rd Qu.:2.000   3rd Qu.: 8.800  
 Max.   :114.00                      Max.   :5.000   Max.   :29.500  </code></pre>
</div>
</div>
<p>That’s better. Now, let’s look at the number of transaction lines over time to see if there are any obvious data issues such as missing data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Count the number of transactions by date</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you! Create a summary of transaction count by date.</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>transaction_counts <span class="ot">&lt;-</span> transactionData[, .N, by <span class="ot">=</span> DATE][<span class="fu">order</span>(DATE)]</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(transaction_counts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         DATE     N
       &lt;Date&gt; &lt;int&gt;
1: 2018-07-01   663
2: 2018-07-02   650
3: 2018-07-03   674
4: 2018-07-04   669
5: 2018-07-05   660
6: 2018-07-06   711</code></pre>
</div>
</div>
<p>There’s only 364 rows, meaning only 364 dates which indicates a missing date. Let’s create a sequence of dates from 1 Jul 2018 to 30 Jun 2019 and use this to create a chart of number of transactions over time to find the missing date.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Create a sequence of dates and join this the count of transactions by date</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you - create a column of dates that includes every day from 1 Jul 2018 to 30 Jun 2019, and join it onto the data to fill in the missing day.</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Get table of all dates</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>all_dates <span class="ot">&lt;-</span> <span class="fu">data.table</span>(<span class="at">DATE =</span> <span class="fu">seq</span>(<span class="fu">as.Date</span>(<span class="st">"2018-07-01"</span>), <span class="fu">as.Date</span>(<span class="st">"2019-06-30"</span>), <span class="at">by =</span> <span class="st">"day"</span>))</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge tables by DATE</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>transactions_by_day <span class="ot">&lt;-</span> <span class="fu">merge</span>(</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  all_dates,</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  transaction_counts,</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="st">"DATE"</span>,</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">all.x =</span> <span class="cn">TRUE</span></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace NA with 0, order by DATE</span></span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>transactions_by_day[<span class="fu">is.na</span>(N), N <span class="sc">:</span><span class="er">=</span> <span class="dv">0</span>]</span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a><span class="fu">setorder</span>(transactions_by_day, DATE)</span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a><span class="do">#### Setting plot themes to format graphs</span></span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span>
<span id="cb36-21"><a href="#cb36-21" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_update</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span>
<span id="cb36-22"><a href="#cb36-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-23"><a href="#cb36-23" aria-hidden="true" tabindex="-1"></a><span class="do">#### Plot transactions over time</span></span>
<span id="cb36-24"><a href="#cb36-24" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(transactions_by_day, <span class="fu">aes</span>(<span class="at">x =</span> DATE, <span class="at">y =</span> N)) <span class="sc">+</span></span>
<span id="cb36-25"><a href="#cb36-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb36-26"><a href="#cb36-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Day"</span>, <span class="at">y =</span> <span class="st">"Number of transactions"</span>, <span class="at">title =</span> <span class="st">"Transactions over time"</span>) <span class="sc">+</span></span>
<span id="cb36-27"><a href="#cb36-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_date</span>(<span class="at">breaks =</span> <span class="st">"1 month"</span>) <span class="sc">+</span></span>
<span id="cb36-28"><a href="#cb36-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="forage_quantium_task1_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can see that there is an increase in purchases in December and a break in late December. Let’s zoom in on this.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Filter to December and look at individual days</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you - recreate the chart above zoomed in to the relevant dates.</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>transactions_by_day_DEC <span class="ot">&lt;-</span> transactions_by_day[<span class="fu">month</span>(DATE) <span class="sc">==</span> <span class="dv">12</span>]</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="do">#### Setting plot themes to format graphs</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_update</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="do">#### Plot transactions over time</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(transactions_by_day_DEC, <span class="fu">aes</span>(<span class="at">x =</span> DATE, <span class="at">y =</span> N)) <span class="sc">+</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Day"</span>, <span class="at">y =</span> <span class="st">"Number of transactions"</span>, <span class="at">title =</span> <span class="st">"Transactions over time"</span>) <span class="sc">+</span></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_x_date</span>(<span class="at">breaks =</span> <span class="st">"1 day"</span>) <span class="sc">+</span></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a><span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="forage_quantium_task1_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can see that the increase in sales occurs in the lead-up to Christmas and that there are zero sales on Christmas day itself. This is due to shops being closed on Christmas day.</p>
<p>Now that we are satisfied that the data no longer has outliers, we can move on to creating other features such as brand of chips or pack size from <code>PROD_NAME</code>. We will start with pack size.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Pack size</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="do">#### We can work this out by taking the digits that are in PROD_NAME</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>transactionData[, PACK_SIZE <span class="sc">:</span><span class="er">=</span> <span class="fu">parse_number</span>(PROD_NAME)]</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="do">#### Always check your output</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="do">#### Let's check if the pack sizes look sensible</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>transactionData[, .N, PACK_SIZE][<span class="fu">order</span>(PACK_SIZE)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    PACK_SIZE     N
        &lt;num&gt; &lt;int&gt;
 1:        70  1507
 2:        90  3008
 3:       110 22387
 4:       125  1454
 5:       134 25102
 6:       135  3257
 7:       150 40203
 8:       160  2970
 9:       165 15297
10:       170 19983
11:       175 66390
12:       180  1468
13:       190  2995
14:       200  4473
15:       210  6272
16:       220  1564
17:       250  3169
18:       270  6285
19:       330 12540
20:       380  6416
    PACK_SIZE     N</code></pre>
</div>
</div>
<p>The largest size is 380g and the smallest size is 70g - seems sensible!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Let's plot a histogram of PACK_SIZE since we know that it is a categorical variable and not a continuous variable even though it is numeric.</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you! Plot a histogram showing the number of transactions by pack size.</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">repr.plot.width =</span> <span class="dv">20</span>, <span class="at">repr.plot.height =</span> <span class="dv">5</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>pack_hist <span class="ot">&lt;-</span> transactionData <span class="sc">%&gt;%</span> </span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>PACK_SIZE)) <span class="sc">+</span> </span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>pack_hist</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="forage_quantium_task1_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Pack sizes created look reasonable.</p>
<p>Now to create brands, we can use the first word in <code>PROD_NAME</code> to work out the brand name…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Brands</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you! Create a column which contains the brand of the product, by extracting it from the product name.</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>transactionData<span class="sc">$</span>BRAND <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="fu">strsplit</span>(transactionData<span class="sc">$</span>PROD_NAME, <span class="st">" "</span>), <span class="st">`</span><span class="at">[</span><span class="st">`</span>, <span class="dv">1</span>)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>transactionData</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              DATE STORE_NBR LYLTY_CARD_NBR TXN_ID PROD_NBR
            &lt;Date&gt;     &lt;int&gt;          &lt;int&gt;  &lt;int&gt;    &lt;int&gt;
     1: 2018-10-17         1           1000      1        5
     2: 2019-05-14         1           1307    348       66
     3: 2019-05-20         1           1343    383       61
     4: 2018-08-17         2           2373    974       69
     5: 2018-08-18         2           2426   1038      108
    ---                                                    
246736: 2019-03-09       272         272319 270088       89
246737: 2018-08-13       272         272358 270154       74
246738: 2018-11-06       272         272379 270187       51
246739: 2018-12-27       272         272379 270188       42
246740: 2018-09-22       272         272380 270189       74
                                       PROD_NAME PROD_QTY TOT_SALES PACK_SIZE
                                          &lt;char&gt;    &lt;int&gt;     &lt;num&gt;     &lt;num&gt;
     1:   Natural Chip        Compny SeaSalt175g        2       6.0       175
     2:                 CCs Nacho Cheese    175g        3       6.3       175
     3:   Smiths Crinkle Cut  Chips Chicken 170g        2       2.9       170
     4:   Smiths Chip Thinly  S/Cream&amp;Onion 175g        5      15.0       175
     5: Kettle Tortilla ChpsHny&amp;Jlpno Chili 150g        3      13.8       150
    ---                                                                      
246736:  Kettle Sweet Chilli And Sour Cream 175g        2      10.8       175
246737:            Tostitos Splash Of  Lime 175g        1       4.4       175
246738:                 Doritos Mexicana    170g        2       8.8       170
246739:  Doritos Corn Chip Mexican Jalapeno 150g        2       7.8       150
246740:            Tostitos Splash Of  Lime 175g        2       8.8       175
           BRAND
          &lt;char&gt;
     1:  Natural
     2:      CCs
     3:   Smiths
     4:   Smiths
     5:   Kettle
    ---         
246736:   Kettle
246737: Tostitos
246738:  Doritos
246739:  Doritos
246740: Tostitos</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Checking brands</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you! Check the results look reasonable.</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>transactionData[, .N, BRAND][<span class="fu">order</span>(BRAND)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         BRAND     N
        &lt;char&gt; &lt;int&gt;
 1:     Burger  1564
 2:        CCs  4551
 3:    Cheetos  2927
 4:   Cheezels  4603
 5:       Cobs  9693
 6:     Dorito  3183
 7:    Doritos 22041
 8:     French  1418
 9:      Grain  6272
10:    GrnWves  1468
11:  Infuzions 11057
12:     Infzns  3144
13:     Kettle 41288
14:        NCC  1419
15:    Natural  6050
16:   Pringles 25102
17:        RRD 11894
18:        Red  4427
19:      Smith  2963
20:     Smiths 27390
21:      Snbts  1576
22:   Sunbites  1432
23:      Thins 14075
24:   Tostitos  9471
25:   Twisties  9454
26:   Tyrrells  6442
27:         WW 10320
28: Woolworths  1516
         BRAND     N</code></pre>
</div>
</div>
<p>Some of the brand names look like they are of the same brands - such as RED and RRD, which are both Red Rock Deli chips. Let’s combine these together.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Clean brand names</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>transactionData[BRAND <span class="sc">==</span> <span class="st">"RED"</span>, BRAND <span class="sc">:</span><span class="er">=</span> <span class="st">"RRD"</span>]</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you! Add any additional brand adjustments you think may be required.</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>transactionData[BRAND <span class="sc">==</span> <span class="st">"Dorito"</span>, BRAND <span class="sc">:</span><span class="er">=</span> <span class="st">"Doritos"</span>]</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>transactionData[BRAND <span class="sc">==</span> <span class="st">"Infzns"</span>, BRAND <span class="sc">:</span><span class="er">=</span> <span class="st">"Infuzions"</span>]</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>transactionData[BRAND <span class="sc">==</span> <span class="st">"Natural"</span>, BRAND <span class="sc">:</span><span class="er">=</span> <span class="st">"NCC"</span>]</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>transactionData[BRAND <span class="sc">==</span> <span class="st">"Smith"</span>, BRAND <span class="sc">:</span><span class="er">=</span> <span class="st">"Smiths"</span>]</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>transactionData[BRAND <span class="sc">==</span> <span class="st">"Snbts"</span>, BRAND <span class="sc">:</span><span class="er">=</span> <span class="st">"Sunbites"</span>]</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>transactionData[BRAND <span class="sc">==</span> <span class="st">"WW"</span>, BRAND <span class="sc">:</span><span class="er">=</span> <span class="st">"Woolworths"</span>]</span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a><span class="do">#### Check again</span></span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you! Check the results look reasonable.</span></span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>transactionData[, .N, BRAND][<span class="fu">order</span>(BRAND)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         BRAND     N
        &lt;char&gt; &lt;int&gt;
 1:     Burger  1564
 2:        CCs  4551
 3:    Cheetos  2927
 4:   Cheezels  4603
 5:       Cobs  9693
 6:    Doritos 25224
 7:     French  1418
 8:      Grain  6272
 9:    GrnWves  1468
10:  Infuzions 14201
11:     Kettle 41288
12:        NCC  7469
13:   Pringles 25102
14:        RRD 11894
15:        Red  4427
16:     Smiths 30353
17:   Sunbites  3008
18:      Thins 14075
19:   Tostitos  9471
20:   Twisties  9454
21:   Tyrrells  6442
22: Woolworths 11836
         BRAND     N</code></pre>
</div>
</div>
</section>
<section id="examining-customer-data" class="level3">
<h3 class="anchored" data-anchor-id="examining-customer-data">Examining customer data</h3>
<p>Now that we are happy with the transaction dataset, let’s have a look at the customer dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Examining customer data</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you! Do some basic summaries of the dataset, including distributions of any key columns.</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(customerData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> LYLTY_CARD_NBR     LIFESTAGE         PREMIUM_CUSTOMER  
 Min.   :   1000   Length:72637       Length:72637      
 1st Qu.:  66202   Class :character   Class :character  
 Median : 134040   Mode  :character   Mode  :character  
 Mean   : 136186                                        
 3rd Qu.: 203375                                        
 Max.   :2373711                                        </code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>customerData[, .N, LIFESTAGE][<span class="fu">order</span>(LIFESTAGE)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                LIFESTAGE     N
                   &lt;char&gt; &lt;int&gt;
1: MIDAGE SINGLES/COUPLES  7275
2:           NEW FAMILIES  2549
3:         OLDER FAMILIES  9780
4:  OLDER SINGLES/COUPLES 14609
5:               RETIREES 14805
6:         YOUNG FAMILIES  9178
7:  YOUNG SINGLES/COUPLES 14441</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>customerData[, .N, PREMIUM_CUSTOMER][<span class="fu">order</span>(PREMIUM_CUSTOMER)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   PREMIUM_CUSTOMER     N
             &lt;char&gt; &lt;int&gt;
1:           Budget 24470
2:       Mainstream 29245
3:          Premium 18922</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Merge transaction data to customer data</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">merge</span>(transactionData, customerData, <span class="at">all.x =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As the number of rows in <code>data</code> is the same as that of <code>transactionData</code>, we can be sure that no duplicates were created. This is because we created <code>data</code> by setting <code>all.x = TRUE</code> (in other words, a left join) which means take all the rows in <code>transactionData</code> and find rows with matching values in shared columns and then joining the details in these rows to the <code>x</code> or the first mentioned table.</p>
<p>Let’s also check if some customers were not matched on by checking for nulls.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you! See if any transactions did not have a matched customer.</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(data, <span class="cf">function</span>(x) <span class="fu">sum</span>(<span class="fu">is.na</span>(x)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  LYLTY_CARD_NBR             DATE        STORE_NBR           TXN_ID 
               0                0                0                0 
        PROD_NBR        PROD_NAME         PROD_QTY        TOT_SALES 
               0                0                0                0 
       PACK_SIZE            BRAND        LIFESTAGE PREMIUM_CUSTOMER 
               0                0                0                0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(transactionData, <span class="cf">function</span>(x) <span class="fu">sum</span>(<span class="fu">is.null</span>(x)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          DATE      STORE_NBR LYLTY_CARD_NBR         TXN_ID       PROD_NBR 
             0              0              0              0              0 
     PROD_NAME       PROD_QTY      TOT_SALES      PACK_SIZE          BRAND 
             0              0              0              0              0 </code></pre>
</div>
</div>
<p>Great, there are no nulls! So all our customers in the transaction data has been accounted for in the customer dataset. Note that if you are continuing with Task 2, you may want to retain this dataset which you can write out as a csv.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fwrite</span>(data, <span class="fu">paste0</span>(filePath,<span class="st">"QVI_data.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Data exploration is now complete!</p>
</section>
</section>
<section id="data-analysis-on-customer-segments" class="level2">
<h2 class="anchored" data-anchor-id="data-analysis-on-customer-segments">Data analysis on customer segments</h2>
<p>Now that the data is ready for analysis, we can define some metrics of interest to the client:</p>
<ul>
<li>Who spends the most on chips (total sales), describing customers by lifestage and how premium their general purchasing behaviour is</li>
<li>How many customers are in each segment</li>
<li>How many chips are bought per customer by segment - What’s the average chip price by customer segment</li>
</ul>
<p>We could also ask our data team for more information. Examples are: - The customer’s total spend over the period and total spend for each transaction to understand what proportion of their grocery spend is on chips - Proportion of customers in each customer segment overall to compare against the mix of customers who purchase chips</p>
<p>Let’s start with calculating total sales by <code>LIFESTAGE</code> and <code>PREMIUM_CUSTOMER</code> and plotting the split by these segments to describe which customer segment contribute most to chip sales.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Total sales by LIFESTAGE and PREMIUM_CUSTOMER</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you! Calculate the summary of sales by those dimensions and create a plot.</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("viridis")</span></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(viridis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: viridisLite</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">repr.plot.width =</span> <span class="dv">10</span>, <span class="at">repr.plot.height =</span> <span class="dv">6</span>)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>sales_summary <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(LIFESTAGE, PREMIUM_CUSTOMER) <span class="sc">%&gt;%</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">TOT_SALES_GROUPED =</span> <span class="fu">sum</span>(TOT_SALES, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'LIFESTAGE'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>sales_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 21 × 3
# Groups:   LIFESTAGE [7]
   LIFESTAGE              PREMIUM_CUSTOMER TOT_SALES_GROUPED
   &lt;chr&gt;                  &lt;chr&gt;                        &lt;dbl&gt;
 1 MIDAGE SINGLES/COUPLES Budget                      33346.
 2 MIDAGE SINGLES/COUPLES Mainstream                  84734.
 3 MIDAGE SINGLES/COUPLES Premium                     54444.
 4 NEW FAMILIES           Budget                      20607.
 5 NEW FAMILIES           Mainstream                  15980.
 6 NEW FAMILIES           Premium                     10761.
 7 OLDER FAMILIES         Budget                     156864.
 8 OLDER FAMILIES         Mainstream                  96414.
 9 OLDER FAMILIES         Premium                     75243.
10 OLDER SINGLES/COUPLES  Budget                     127834.
# ℹ 11 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>plot_sales_life_customer <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(sales_summary, <span class="fu">aes</span>(<span class="at">x =</span> LIFESTAGE, <span class="at">y =</span> TOT_SALES_GROUPED, <span class="at">fill =</span> PREMIUM_CUSTOMER)) <span class="sc">+</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Total Sales by Lifestage and Premium Customer"</span>,</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Lifestage"</span>,</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Total Sales"</span>,</span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Premium Customer"</span>) <span class="sc">+</span></span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a>plot_sales_life_customer</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="forage_quantium_task1_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Sales are coming mainly from <code>Budget - older families</code>, <code>Mainstream - young singles/couples</code>, and <code>Mainstream - retirees</code>.</p>
<p>Let’s see if the higher sales are due to there being more customers who buy chips.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Number of customers by LIFESTAGE and PREMIUM_CUSTOMER</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you! Calculate the summary of number of customers by those dimensions and create a plot.</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">repr.plot.width =</span> <span class="dv">10</span>, <span class="at">repr.plot.height =</span> <span class="dv">6</span>)</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>count_summary <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(LIFESTAGE, PREMIUM_CUSTOMER) <span class="sc">%&gt;%</span></span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">NUM_IDS =</span> <span class="fu">n_distinct</span>(LYLTY_CARD_NBR))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'LIFESTAGE'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>count_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 21 × 3
# Groups:   LIFESTAGE [7]
   LIFESTAGE              PREMIUM_CUSTOMER NUM_IDS
   &lt;chr&gt;                  &lt;chr&gt;              &lt;int&gt;
 1 MIDAGE SINGLES/COUPLES Budget              1474
 2 MIDAGE SINGLES/COUPLES Mainstream          3298
 3 MIDAGE SINGLES/COUPLES Premium             2369
 4 NEW FAMILIES           Budget              1087
 5 NEW FAMILIES           Mainstream           830
 6 NEW FAMILIES           Premium              575
 7 OLDER FAMILIES         Budget              4611
 8 OLDER FAMILIES         Mainstream          2788
 9 OLDER FAMILIES         Premium             2231
10 OLDER SINGLES/COUPLES  Budget              4849
# ℹ 11 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>plot_num_life_customer <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(count_summary, <span class="fu">aes</span>(<span class="at">x =</span> LIFESTAGE, <span class="at">y =</span> NUM_IDS, <span class="at">fill =</span> PREMIUM_CUSTOMER)) <span class="sc">+</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Total Number of Customers by Lifestage and Premium Customer"</span>,</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Lifestage"</span>,</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Distinct Customer Count"</span>,</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Premium Customer"</span>) <span class="sc">+</span></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a>plot_num_life_customer</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="forage_quantium_task1_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>There are more <code>Mainstream - young singles/couples</code> and <code>Mainstream - retirees</code> who buy chips. This contributes to there being more sales to these customer segments but this is not a major driver for the <code>Budget - Older families</code> segment. Higher sales may also be driven by more units of chips being bought per customer.</p>
<p>Let’s have a look at this next.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Average number of units per customer by LIFESTAGE and PREMIUM_CUSTOMER</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you! Calculate and plot the average number of units per customer by those two dimensions.</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>priceperunit_summary <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(LIFESTAGE, PREMIUM_CUSTOMER) <span class="sc">%&gt;%</span></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">PROD_QTY_GROUPED =</span> <span class="fu">sum</span>(PROD_QTY, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'LIFESTAGE'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>priceperunit_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 21 × 3
# Groups:   LIFESTAGE [7]
   LIFESTAGE              PREMIUM_CUSTOMER PROD_QTY_GROUPED
   &lt;chr&gt;                  &lt;chr&gt;                       &lt;int&gt;
 1 MIDAGE SINGLES/COUPLES Budget                       8883
 2 MIDAGE SINGLES/COUPLES Mainstream                  21213
 3 MIDAGE SINGLES/COUPLES Premium                     14400
 4 NEW FAMILIES           Budget                       5241
 5 NEW FAMILIES           Mainstream                   4060
 6 NEW FAMILIES           Premium                      2769
 7 OLDER FAMILIES         Budget                      41853
 8 OLDER FAMILIES         Mainstream                  25804
 9 OLDER FAMILIES         Premium                     20239
10 OLDER SINGLES/COUPLES  Budget                      32883
# ℹ 11 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>avg_summary <span class="ot">&lt;-</span> <span class="fu">merge</span>(</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  sales_summary,</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>  count_summary,</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"LIFESTAGE"</span>, <span class="st">"PREMIUM_CUSTOMER"</span>),</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">all.x =</span> <span class="cn">TRUE</span></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">merge</span>(priceperunit_summary, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"LIFESTAGE"</span>, <span class="st">"PREMIUM_CUSTOMER"</span>), <span class="at">all.x =</span> <span class="cn">TRUE</span>)</span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>avg_summary<span class="sc">$</span>AVG_UNIT_PER_CUST <span class="ot">=</span> (avg_summary<span class="sc">$</span>PROD_QTY_GROUPED <span class="sc">/</span> avg_summary<span class="sc">$</span>NUM_IDS)</span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a>avg_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                LIFESTAGE PREMIUM_CUSTOMER TOT_SALES_GROUPED NUM_IDS
1  MIDAGE SINGLES/COUPLES           Budget          33345.70    1474
2  MIDAGE SINGLES/COUPLES       Mainstream          84734.25    3298
3  MIDAGE SINGLES/COUPLES          Premium          54443.85    2369
4            NEW FAMILIES           Budget          20607.45    1087
5            NEW FAMILIES       Mainstream          15979.70     830
6            NEW FAMILIES          Premium          10760.80     575
7          OLDER FAMILIES           Budget         156863.75    4611
8          OLDER FAMILIES       Mainstream          96413.55    2788
9          OLDER FAMILIES          Premium          75242.60    2231
10  OLDER SINGLES/COUPLES           Budget         127833.60    4849
11  OLDER SINGLES/COUPLES       Mainstream         124648.50    4858
12  OLDER SINGLES/COUPLES          Premium         123537.55    4682
13               RETIREES           Budget         105916.30    4385
14               RETIREES       Mainstream         145168.95    6358
15               RETIREES          Premium          91296.65    3812
16         YOUNG FAMILIES           Budget         129717.95    3953
17         YOUNG FAMILIES       Mainstream          86338.25    2685
18         YOUNG FAMILIES          Premium          78571.70    2398
19  YOUNG SINGLES/COUPLES           Budget          57122.10    3647
20  YOUNG SINGLES/COUPLES       Mainstream         147582.20    7917
21  YOUNG SINGLES/COUPLES          Premium          39052.30    2480
   PROD_QTY_GROUPED AVG_UNIT_PER_CUST
1              8883          6.026459
2             21213          6.432080
3             14400          6.078514
4              5241          4.821527
5              4060          4.891566
6              2769          4.815652
7             41853          9.076773
8             25804          9.255380
9             20239          9.071717
10            32883          6.781398
11            32607          6.712021
12            31695          6.769543
13            26932          6.141847
14            37677          5.925920
15            23266          6.103358
16            34482          8.722995
17            23194          8.638361
18            20901          8.716013
19            15500          4.250069
20            36225          4.575597
21            10575          4.264113</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>plot_avg_life_customer <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(avg_summary, <span class="fu">aes</span>(<span class="at">x =</span> LIFESTAGE, <span class="at">y =</span> AVG_UNIT_PER_CUST, <span class="at">fill =</span> PREMIUM_CUSTOMER)) <span class="sc">+</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Average Number of Units per Customer by Lifestage and Premium Customer"</span>,</span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Lifestage"</span>,</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Average Number of Units per Customer"</span>,</span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Premium Customer"</span>) <span class="sc">+</span></span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb78-8"><a href="#cb78-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span>
<span id="cb78-9"><a href="#cb78-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-10"><a href="#cb78-10" aria-hidden="true" tabindex="-1"></a>plot_avg_life_customer</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="forage_quantium_task1_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Older families and young families in general buy more chips per customer. Let’s also investigate the average price per unit chips bought for each customer segment as this is also a driver of total sales.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Average price per unit by LIFESTAGE and PREMIUM_CUSTOMER</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you! Calculate and plot the average price per unit sold (average sale price) by those two customer dimensions.</span></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>avg_summary<span class="sc">$</span>AVG_PRICE_PER_UNIT <span class="ot">=</span> (avg_summary<span class="sc">$</span>TOT_SALES_GROUPED <span class="sc">/</span> avg_summary<span class="sc">$</span>PROD_QTY_GROUPED)</span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>avg_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                LIFESTAGE PREMIUM_CUSTOMER TOT_SALES_GROUPED NUM_IDS
1  MIDAGE SINGLES/COUPLES           Budget          33345.70    1474
2  MIDAGE SINGLES/COUPLES       Mainstream          84734.25    3298
3  MIDAGE SINGLES/COUPLES          Premium          54443.85    2369
4            NEW FAMILIES           Budget          20607.45    1087
5            NEW FAMILIES       Mainstream          15979.70     830
6            NEW FAMILIES          Premium          10760.80     575
7          OLDER FAMILIES           Budget         156863.75    4611
8          OLDER FAMILIES       Mainstream          96413.55    2788
9          OLDER FAMILIES          Premium          75242.60    2231
10  OLDER SINGLES/COUPLES           Budget         127833.60    4849
11  OLDER SINGLES/COUPLES       Mainstream         124648.50    4858
12  OLDER SINGLES/COUPLES          Premium         123537.55    4682
13               RETIREES           Budget         105916.30    4385
14               RETIREES       Mainstream         145168.95    6358
15               RETIREES          Premium          91296.65    3812
16         YOUNG FAMILIES           Budget         129717.95    3953
17         YOUNG FAMILIES       Mainstream          86338.25    2685
18         YOUNG FAMILIES          Premium          78571.70    2398
19  YOUNG SINGLES/COUPLES           Budget          57122.10    3647
20  YOUNG SINGLES/COUPLES       Mainstream         147582.20    7917
21  YOUNG SINGLES/COUPLES          Premium          39052.30    2480
   PROD_QTY_GROUPED AVG_UNIT_PER_CUST AVG_PRICE_PER_UNIT
1              8883          6.026459           3.753878
2             21213          6.432080           3.994449
3             14400          6.078514           3.780823
4              5241          4.821527           3.931969
5              4060          4.891566           3.935887
6              2769          4.815652           3.886168
7             41853          9.076773           3.747969
8             25804          9.255380           3.736380
9             20239          9.071717           3.717703
10            32883          6.781398           3.887529
11            32607          6.712021           3.822753
12            31695          6.769543           3.897698
13            26932          6.141847           3.932731
14            37677          5.925920           3.852986
15            23266          6.103358           3.924037
16            34482          8.722995           3.761903
17            23194          8.638361           3.722439
18            20901          8.716013           3.759232
19            15500          4.250069           3.685297
20            36225          4.575597           4.074043
21            10575          4.264113           3.692889</code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>plot_avg_life_customer <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(avg_summary, <span class="fu">aes</span>(<span class="at">x =</span> LIFESTAGE, <span class="at">y =</span> AVG_PRICE_PER_UNIT, <span class="at">fill =</span> PREMIUM_CUSTOMER)) <span class="sc">+</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Average Price per Unit by Lifestage and Premium Customer"</span>,</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Lifestage"</span>,</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Average Price per Unit"</span>,</span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Premium Customer"</span>) <span class="sc">+</span></span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-10"><a href="#cb81-10" aria-hidden="true" tabindex="-1"></a>plot_avg_life_customer</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="forage_quantium_task1_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p><code>Mainstream - midage singles/couples</code> and <code>Mainstream - young singles/couples</code> are more willing to pay more per packet of chips compared to their budget and premium counterparts. This may be due to premium shoppers being more likely to buy healthy snacks and when they buy chips, this is mainly for entertainment purposes rather than their own consumption.</p>
<p>This is also supported by there being fewer premium <code>Premium - midage singles/couples</code> and <code>Premium - young singles/couples</code> buying chips compared to their mainstream counterparts.</p>
<p>As the difference in average price per unit isn’t large, we can check if this difference is statistically different.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Perform an independent t-test between mainstream vs premium and budget midage young singles and couples</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you! Perform a t-test to see if the difference is significant.</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>filtered_data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(LIFESTAGE <span class="sc">==</span> <span class="fu">c</span>(<span class="st">"MIDAGE SINGLES/COUPLES"</span>, <span class="st">"YOUNG SINGLES/COUPLES"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">GROUP =</span> <span class="fu">ifelse</span>(PREMIUM_CUSTOMER <span class="sc">==</span> <span class="st">"Mainstream"</span>, <span class="st">"Mainstream"</span>, <span class="st">"Non_Mainstream"</span>))</span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(filtered_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Key: &lt;LYLTY_CARD_NBR&gt;
   LYLTY_CARD_NBR       DATE STORE_NBR TXN_ID PROD_NBR
            &lt;int&gt;     &lt;Date&gt;     &lt;int&gt;  &lt;int&gt;    &lt;int&gt;
1:           1002 2018-09-16         1      2       58
2:           1007 2018-12-05         1      8       10
3:           1010 2018-09-09         1     10       51
4:           1018 2018-09-03         1     22        3
5:           1018 2019-06-20         1     24       38
6:           1020 2018-08-16         1     26       19
                                  PROD_NAME PROD_QTY TOT_SALES PACK_SIZE
                                     &lt;char&gt;    &lt;int&gt;     &lt;num&gt;     &lt;num&gt;
1:    Red Rock Deli Chikn&amp;Garlic Aioli 150g        1       2.7       150
2:      RRD SR Slow Rst     Pork Belly 150g        1       2.7       150
3:                 Doritos Mexicana    170g        2       8.8       170
4: Kettle Sensations   Camembert &amp; Fig 150g        1       4.6       150
5:  Infuzions Mango     Chutny Papadums 70g        1       2.4        70
6:      Smiths Crinkle Cut  Snag&amp;Sauce 150g        1       2.6       150
       BRAND             LIFESTAGE PREMIUM_CUSTOMER          GROUP
      &lt;char&gt;                &lt;char&gt;           &lt;char&gt;         &lt;char&gt;
1:       Red YOUNG SINGLES/COUPLES       Mainstream     Mainstream
2:       RRD YOUNG SINGLES/COUPLES           Budget Non_Mainstream
3:   Doritos YOUNG SINGLES/COUPLES       Mainstream     Mainstream
4:    Kettle YOUNG SINGLES/COUPLES       Mainstream     Mainstream
5: Infuzions YOUNG SINGLES/COUPLES       Mainstream     Mainstream
6:    Smiths YOUNG SINGLES/COUPLES       Mainstream     Mainstream</code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>ttest <span class="ot">&lt;-</span> <span class="fu">t.test</span>(TOT_SALES <span class="sc">~</span> GROUP, <span class="at">data =</span> filtered_data)</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>ttest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Welch Two Sample t-test

data: TOT_SALES by GROUP
t = 22.456, df = 27326, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means between group Mainstream and
group Non_Mainstream is not equal to 0
95 percent confidence interval:
0.6142873 0.7317767
sample estimates:
mean in group Mainstream mean in group Non_Mainstream
7.563116 6.890084</code></pre>
</div>
</div>
<p>The t-test results in a p-value of 1.121045^{-110}, i.e.&nbsp;the unit price for mainstream, young and mid-age singles and couples [<code>ARE</code> / ARE NOT] significantly higher than that of budget or premium, young and midage singles and couples.</p>
</section>
<section id="deep-dive-into-specific-customer-segments-for-insights" class="level2">
<h2 class="anchored" data-anchor-id="deep-dive-into-specific-customer-segments-for-insights">Deep dive into specific customer segments for insights</h2>
<p>We have found quite a few interesting insights that we can dive deeper into.</p>
<p>We might want to target customer segments that contribute the most to sales to retain them or further increase sales. Let’s look at <code>Mainstream - young singles/couples</code>. For instance, let’s find out if they tend to buy a particular brand of chips.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Deep dive into Mainstream, young singles/couples</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you! Work out of there are brands that these two customer segments prefer more than others. You could use a technique called affinity analysis or a-priori analysis (or any other method if you prefer)</span></span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(arules)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'arules'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    abbreviate, write</code></pre>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(arulesViz)</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RColorBrewer)</span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'tidyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:Matrix':

    expand, pack, unpack</code></pre>
</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtered dataset</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>filtered_main_ysc <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(LIFESTAGE <span class="sc">==</span> <span class="st">"YOUNG SINGLES/COUPLES"</span>, PREMIUM_CUSTOMER <span class="sc">==</span> <span class="st">"Mainstream"</span>)</span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(filtered_main_ysc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Key: &lt;LYLTY_CARD_NBR&gt;
   LYLTY_CARD_NBR       DATE STORE_NBR TXN_ID PROD_NBR
            &lt;int&gt;     &lt;Date&gt;     &lt;int&gt;  &lt;int&gt;    &lt;int&gt;
1:           1002 2018-09-16         1      2       58
2:           1010 2018-09-09         1     10       51
3:           1018 2018-09-03         1     22        3
4:           1018 2018-11-28         1     23       97
5:           1018 2019-06-20         1     24       38
6:           1020 2018-08-16         1     26       19
                                  PROD_NAME PROD_QTY TOT_SALES PACK_SIZE
                                     &lt;char&gt;    &lt;int&gt;     &lt;num&gt;     &lt;num&gt;
1:    Red Rock Deli Chikn&amp;Garlic Aioli 150g        1       2.7       150
2:                 Doritos Mexicana    170g        2       8.8       170
3: Kettle Sensations   Camembert &amp; Fig 150g        1       4.6       150
4:                 RRD Salt &amp; Vinegar  165g        1       3.0       165
5:  Infuzions Mango     Chutny Papadums 70g        1       2.4        70
6:      Smiths Crinkle Cut  Snag&amp;Sauce 150g        1       2.6       150
       BRAND             LIFESTAGE PREMIUM_CUSTOMER
      &lt;char&gt;                &lt;char&gt;           &lt;char&gt;
1:       Red YOUNG SINGLES/COUPLES       Mainstream
2:   Doritos YOUNG SINGLES/COUPLES       Mainstream
3:    Kettle YOUNG SINGLES/COUPLES       Mainstream
4:       RRD YOUNG SINGLES/COUPLES       Mainstream
5: Infuzions YOUNG SINGLES/COUPLES       Mainstream
6:    Smiths YOUNG SINGLES/COUPLES       Mainstream</code></pre>
</div>
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Transform into transactions</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="co"># https://www.geeksforgeeks.org/apriori-algorithm-in-r-programming/</span></span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>trans_data_brand <span class="ot">&lt;-</span> <span class="fu">as</span>(<span class="fu">split</span>(filtered_main_ysc<span class="sc">$</span>BRAND, filtered_main_ysc<span class="sc">$</span>TXN_ID), <span class="st">"transactions"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in asMethod(object): removing duplicated items in transactions</code></pre>
</div>
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtain and look into association rules</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>apriori_rules_brand <span class="ot">&lt;-</span> <span class="fu">apriori</span>(trans_data_brand, <span class="at">parameter =</span> <span class="fu">list</span>(<span class="at">supp =</span> <span class="fl">0.1</span>, <span class="at">conf =</span> <span class="fl">0.1</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Apriori

Parameter specification:
 confidence minval smax arem  aval originalSupport maxtime support minlen
        0.1    0.1    1 none FALSE            TRUE       5     0.1      1
 maxlen target  ext
     10  rules TRUE

Algorithmic control:
 filter tree heap memopt load sort verbose
    0.1 TRUE TRUE  FALSE TRUE    2    TRUE

Absolute minimum support count: 1948 

set item appearances ...[0 item(s)] done [0.00s].
set transactions ...[22 item(s), 19482 transaction(s)] done [0.00s].
sorting and recoding items ... [3 item(s)] done [0.00s].
creating transaction tree ... done [0.00s].
checking subsets of size 1 2 done [0.00s].
writing ... [3 rule(s)] done [0.00s].
creating S4 object  ... done [0.00s].</code></pre>
</div>
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">inspect</span>(apriori_rules_brand[<span class="dv">1</span><span class="sc">:</span><span class="fu">min</span>(<span class="dv">10</span>, <span class="fu">length</span>(apriori_rules_brand))]) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    lhs    rhs        support   confidence coverage lift count
[1] {}  =&gt; {Pringles} 0.1188276 0.1188276  1        1    2315 
[2] {}  =&gt; {Doritos}  0.1220614 0.1220614  1        1    2378 
[3] {}  =&gt; {Kettle}   0.1973103 0.1973103  1        1    3844 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bar plot to inspect the distribution of objects based on the transactions for item frequencies/support</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>max_freq_brand <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="fu">itemFrequency</span>(trans_data_brand, <span class="at">type =</span> <span class="st">"relative"</span>))</span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a>arules<span class="sc">::</span><span class="fu">itemFrequencyPlot</span>(trans_data_brand, <span class="at">topN =</span> <span class="dv">20</span>, </span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">col =</span> <span class="fu">brewer.pal</span>(<span class="dv">8</span>, <span class="st">'Pastel2'</span>),</span>
<span id="cb102-5"><a href="#cb102-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">main =</span> <span class="st">'Relative Brand Frequency Plot'</span>,</span>
<span id="cb102-6"><a href="#cb102-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">type =</span> <span class="st">"relative"</span>,</span>
<span id="cb102-7"><a href="#cb102-7" aria-hidden="true" tabindex="-1"></a>                          <span class="at">xlab =</span> <span class="st">"Brand"</span>,</span>
<span id="cb102-8"><a href="#cb102-8" aria-hidden="true" tabindex="-1"></a>                          <span class="at">ylab =</span> <span class="st">"Frequency (Relative)"</span>,</span>
<span id="cb102-9"><a href="#cb102-9" aria-hidden="true" tabindex="-1"></a>                          <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, max_freq_brand <span class="sc">+</span> <span class="fl">0.05</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="forage_quantium_task1_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can see that : Kettle provides the greatest item frequency of 0.1973103, which is significantly greater than the corresponding item frequencies for Doritos and Pringles at 0.1220614 and 0.1188276 respectively. As such, it can be inferred that customers under the segment <code>Mainstream - young singles/couples</code> particularly prefer <code>"Kettle"</code> brand chips.</p>
<p>Let’s also find out if our target segment tends to buy larger packs of chips.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Preferred pack size compared to the rest of the population</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Over to you! Do the same for pack size.</span></span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-4"><a href="#cb103-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(filtered_main_ysc, <span class="fu">aes</span>(<span class="at">x =</span> PACK_SIZE)) <span class="sc">+</span></span>
<span id="cb103-5"><a href="#cb103-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb103-6"><a href="#cb103-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Density Plot of Pack Size"</span>,</span>
<span id="cb103-7"><a href="#cb103-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Pack Size (g)"</span>,</span>
<span id="cb103-8"><a href="#cb103-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb103-9"><a href="#cb103-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="forage_quantium_task1_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> PACK_SIZE)) <span class="sc">+</span></span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Density Plot of Pack Size"</span>,</span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Pack Size (g)"</span>,</span>
<span id="cb104-5"><a href="#cb104-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb104-6"><a href="#cb104-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="forage_quantium_task1_files/figure-html/unnamed-chunk-17-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtered dataset</span></span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>filtered_main_ysc <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(LIFESTAGE <span class="sc">==</span> <span class="st">"YOUNG SINGLES/COUPLES"</span>, PREMIUM_CUSTOMER <span class="sc">==</span> <span class="st">"Mainstream"</span>)</span>
<span id="cb105-4"><a href="#cb105-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(filtered_main_ysc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Key: &lt;LYLTY_CARD_NBR&gt;
   LYLTY_CARD_NBR       DATE STORE_NBR TXN_ID PROD_NBR
            &lt;int&gt;     &lt;Date&gt;     &lt;int&gt;  &lt;int&gt;    &lt;int&gt;
1:           1002 2018-09-16         1      2       58
2:           1010 2018-09-09         1     10       51
3:           1018 2018-09-03         1     22        3
4:           1018 2018-11-28         1     23       97
5:           1018 2019-06-20         1     24       38
6:           1020 2018-08-16         1     26       19
                                  PROD_NAME PROD_QTY TOT_SALES PACK_SIZE
                                     &lt;char&gt;    &lt;int&gt;     &lt;num&gt;     &lt;num&gt;
1:    Red Rock Deli Chikn&amp;Garlic Aioli 150g        1       2.7       150
2:                 Doritos Mexicana    170g        2       8.8       170
3: Kettle Sensations   Camembert &amp; Fig 150g        1       4.6       150
4:                 RRD Salt &amp; Vinegar  165g        1       3.0       165
5:  Infuzions Mango     Chutny Papadums 70g        1       2.4        70
6:      Smiths Crinkle Cut  Snag&amp;Sauce 150g        1       2.6       150
       BRAND             LIFESTAGE PREMIUM_CUSTOMER
      &lt;char&gt;                &lt;char&gt;           &lt;char&gt;
1:       Red YOUNG SINGLES/COUPLES       Mainstream
2:   Doritos YOUNG SINGLES/COUPLES       Mainstream
3:    Kettle YOUNG SINGLES/COUPLES       Mainstream
4:       RRD YOUNG SINGLES/COUPLES       Mainstream
5: Infuzions YOUNG SINGLES/COUPLES       Mainstream
6:    Smiths YOUNG SINGLES/COUPLES       Mainstream</code></pre>
</div>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Transform into transactions</span></span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a><span class="co"># https://www.geeksforgeeks.org/apriori-algorithm-in-r-programming/</span></span>
<span id="cb107-3"><a href="#cb107-3" aria-hidden="true" tabindex="-1"></a>trans_data_pack <span class="ot">&lt;-</span> <span class="fu">as</span>(<span class="fu">split</span>(filtered_main_ysc<span class="sc">$</span>BRAND, filtered_main_ysc<span class="sc">$</span>TXN_ID), <span class="st">"transactions"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in asMethod(object): removing duplicated items in transactions</code></pre>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get item frequencies</span></span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a>freqs <span class="ot">&lt;-</span> <span class="fu">itemFrequency</span>(trans_data_pack, <span class="at">type =</span> <span class="st">"relative"</span>)</span>
<span id="cb109-3"><a href="#cb109-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb109-4"><a href="#cb109-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert item names (pack sizes) to numeric</span></span>
<span id="cb109-5"><a href="#cb109-5" aria-hidden="true" tabindex="-1"></a>pack_sizes <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">names</span>(freqs))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: NAs introduced by coercion</code></pre>
</div>
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Order by numeric pack size</span></span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>ordered_indices <span class="ot">&lt;-</span> <span class="fu">order</span>(pack_sizes)</span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a>ordered_freqs <span class="ot">&lt;-</span> freqs[ordered_indices]</span>
<span id="cb111-4"><a href="#cb111-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-5"><a href="#cb111-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot as barplot</span></span>
<span id="cb111-6"><a href="#cb111-6" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(ordered_freqs[<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>], </span>
<span id="cb111-7"><a href="#cb111-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">names.arg =</span> <span class="fu">names</span>(ordered_freqs)[<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>],</span>
<span id="cb111-8"><a href="#cb111-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="fu">brewer.pal</span>(<span class="dv">8</span>, <span class="st">'Pastel2'</span>),</span>
<span id="cb111-9"><a href="#cb111-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Relative Pack Size Frequency Plot (Ordered by Pack Size)"</span>,</span>
<span id="cb111-10"><a href="#cb111-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Pack Size"</span>,</span>
<span id="cb111-11"><a href="#cb111-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Frequency (Relative)"</span>,</span>
<span id="cb111-12"><a href="#cb111-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">las =</span> <span class="dv">2</span>,  <span class="co"># rotate x labels</span></span>
<span id="cb111-13"><a href="#cb111-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">max</span>(ordered_freqs[<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>]) <span class="sc">+</span> <span class="fl">0.05</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="forage_quantium_task1_files/figure-html/unnamed-chunk-17-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In the density plots, there are more peaks in density on the lower end of the range of <code>PACK_SIZE</code> values for both customers under the segment <code>Mainstream - young singles/couples</code> and across the overall data. As such, while the target segment <code>Mainstream - young singles/couples</code> tends towards purchasing smaller packs of chips, this characteristic does not appear to be unique to the given segment. A similar result is also demonstrated in the item frequency plot ordered by <code>PACK_SIZE</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(viridis)</span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a>segment_summary <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb112-4"><a href="#cb112-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(LIFESTAGE, PREMIUM_CUSTOMER) <span class="sc">%&gt;%</span></span>
<span id="cb112-5"><a href="#cb112-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb112-6"><a href="#cb112-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(LIFESTAGE) <span class="sc">%&gt;%</span></span>
<span id="cb112-7"><a href="#cb112-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop_within_lifestage =</span> count <span class="sc">/</span> <span class="fu">sum</span>(count)) <span class="sc">%&gt;%</span></span>
<span id="cb112-8"><a href="#cb112-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(PREMIUM_CUSTOMER) <span class="sc">%&gt;%</span></span>
<span id="cb112-9"><a href="#cb112-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop_within_premium =</span> count <span class="sc">/</span> <span class="fu">sum</span>(count)) <span class="sc">%&gt;%</span></span>
<span id="cb112-10"><a href="#cb112-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb112-11"><a href="#cb112-11" aria-hidden="true" tabindex="-1"></a>segment_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 21 × 5
   LIFESTAGE    PREMIUM_CUSTOMER count prop_within_lifestage prop_within_premium
   &lt;chr&gt;        &lt;chr&gt;            &lt;int&gt;                 &lt;dbl&gt;               &lt;dbl&gt;
 1 MIDAGE SING… Budget            4691                 0.200              0.0541
 2 MIDAGE SING… Mainstream       11095                 0.474              0.117 
 3 MIDAGE SING… Premium           7612                 0.325              0.117 
 4 NEW FAMILIES Budget            2824                 0.435              0.0325
 5 NEW FAMILIES Mainstream        2185                 0.336              0.0230
 6 NEW FAMILIES Premium           1488                 0.229              0.0229
 7 OLDER FAMIL… Budget           21514                 0.476              0.248 
 8 OLDER FAMIL… Mainstream       13241                 0.293              0.139 
 9 OLDER FAMIL… Premium          10403                 0.230              0.160 
10 OLDER SINGL… Budget           17172                 0.338              0.198 
# ℹ 11 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(segment_summary, <span class="fu">aes</span>(<span class="at">x =</span> PREMIUM_CUSTOMER, <span class="at">y =</span> LIFESTAGE, <span class="at">fill =</span> count)) <span class="sc">+</span></span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>(<span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb114-3"><a href="#cb114-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis</span>(<span class="at">name =</span> <span class="st">"Count"</span>, <span class="at">option =</span> <span class="st">"D"</span>, <span class="at">begin =</span> <span class="dv">0</span>, <span class="at">end =</span> <span class="dv">1</span>, <span class="at">direction =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb114-4"><a href="#cb114-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Count of Customers by Segment"</span>,</span>
<span id="cb114-5"><a href="#cb114-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Premium Customer Status"</span>, <span class="at">y =</span> <span class="st">"Lifestage"</span>, <span class="at">fill =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb114-6"><a href="#cb114-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="forage_quantium_task1_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(segment_summary, <span class="fu">aes</span>(<span class="at">x =</span> PREMIUM_CUSTOMER, <span class="at">y =</span> LIFESTAGE, <span class="at">fill =</span> prop_within_lifestage)) <span class="sc">+</span></span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>(<span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb115-3"><a href="#cb115-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis</span>(<span class="at">name =</span> <span class="st">"Proportion"</span>, <span class="at">option =</span> <span class="st">"C"</span>) <span class="sc">+</span></span>
<span id="cb115-4"><a href="#cb115-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Proportion within Lifestage"</span>,</span>
<span id="cb115-5"><a href="#cb115-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Premium Customer Status"</span>, <span class="at">y =</span> <span class="st">"Lifestage"</span>, <span class="at">fill =</span> <span class="st">"Proportion"</span>) <span class="sc">+</span></span>
<span id="cb115-6"><a href="#cb115-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="forage_quantium_task1_files/figure-html/unnamed-chunk-18-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(segment_summary, <span class="fu">aes</span>(<span class="at">x =</span> PREMIUM_CUSTOMER, <span class="at">y =</span> LIFESTAGE, <span class="at">fill =</span> prop_within_premium)) <span class="sc">+</span></span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>(<span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb116-3"><a href="#cb116-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis</span>(<span class="at">name =</span> <span class="st">"Proportion"</span>, <span class="at">option =</span> <span class="st">"C"</span>) <span class="sc">+</span></span>
<span id="cb116-4"><a href="#cb116-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Proportion within Premium Customer Type"</span>,</span>
<span id="cb116-5"><a href="#cb116-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Premium Customer Status"</span>, <span class="at">y =</span> <span class="st">"Lifestage"</span>, <span class="at">fill =</span> <span class="st">"Proportion"</span>) <span class="sc">+</span></span>
<span id="cb116-6"><a href="#cb116-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="forage_quantium_task1_files/figure-html/unnamed-chunk-18-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>